name: HappyOm
favicon: null
layout_spectrum: 0.45728
typography_spectrum: 0.75141
title: 'Get Happy !'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e883c5'
    - '#b9e6bd'
    - '#000000'
    - '#66666c'
    - '#fefefe'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
