name: HappyOm
favicon: null
layout_spectrum: 0.873311452800408
typography_spectrum: 0.17017547180876136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6871129926294088
  lightness: 0.4855307540856302
  saturation: 0.08775027235969901
  rhythmicContrast: 0.37254316080361605
purpose: []
