name: HappyOm
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75141
title: 'Get Happy !'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#edaa73'
    - '#b96831'
    - '#af45c3'
  brandStrength: 0.6875
  lightness: 0.4855307540856302
  saturation: 0
  rhythmicContrast: 0.37254316080361605
purpose: []
